### PR TITLE
Add mocking framework

### PR DESCRIPTION
**Pull request by dhoepelman**
Patch to add Mockito and Powermock dependency to core/pom.xml.
See https://github.com/delftsre/assignments-2013/issues/2 and the [vote](http://doodle.com/sgk8eng5rf6ieex2)

### CODE REVIEW

**Comment by gousiosg** [comment]
Why did you include it on 'alitheia/pom.xml' and not on the top-level 'pom.xml' file?

**Comment by gousiosg** [comment]
Also, before merging, I want all commits squashed to one. c440093 should be removed of fixed.

**Comment by dhoepelman** [comment]
I presume you mean `alitheia/core/pom.xml` (because that is the file that is changed)? I added it there because [/alitheia/pom.xml](https://github.com/istlab/Alitheia-Core/blob/master/alitheia/pom.xml) and [/pom.xml](https://github.com/istlab/Alitheia-Core/blob/master/pom.xml) currently do not contain any dependencies.

I don't know how adding to /pom.xml will work out, most non-core parts seem to use Junit 3.8 and Mockito needs Junit 4

I managed to rebase, the IDE.md commits are gone now.

**Comment by Xyclade** [comment]
It is not possible to add dependencies to the root pom.xml, at least not as far as I'm concerned. So adding them in alitheia/core/pom.xml seems right to me.

**Comment by dhoepelman** [comment]
The commits are squashed and downstream is merged, so could this be merged into upstream?

**Comment by Apanatshka** [comment]
@gousiosg what's the hold up on this? I think everyone can really use this dependency.

**Pull request merged**
