### PR TITLE
Changed java version to 1.7 in order to support newest features.

### PR DESCRIPTION
**Pull request by Apanatshka**
Probably handy for everyone involved. Only changed version in pom file, but apparently whitespace was changed so GitHub doesn't display changes nicely. Checked if it still builds, and it does.

### CODE REVIEW

**Comment by dufernst** [comment]
Git diff gives the following changes:
https://gist.github.com/dufernst/8052509
The file encoding has probably changed when you edited it resulting in git thinking everything has changed.

**Comment by Apanatshka** [comment]
Thanks for sharing that, I see we inadvertently left in the H2 -> MySQL change! We'll fix that ASAP

**Comment by dufernst** [comment]
Hadn't noticed that, even thought it would be useful to have the default set to mysql (as it is suggested to be the default by the setup guides), it might not be proper indeed change that in this commit/pull request.

**Comment by gousiosg** [comment]
Your patch is not correct as it overrides the authorship info of the whole pom.xml file, even though you only changed 2 lines. Please update this PR with a correct patch.

**Comment by Apanatshka** [comment]
I've corrected the file encoding issue and rebased everything to one commit again. 

@gousiosg off-topic question: would you also be interested in a change from using H2 as the standard database to using MySQL as the standard database? The README currently advises MySQL.

**Comment by gousiosg** [comment]
Thanks! WRT H2, I would prefer to have it as default, because it is the only option to have Alitheia Core running without external dependencies.

**Pull request merged**
