### PR TITLE
Updated README.md and IDE.md

### PR DESCRIPTION
**Pull request by elwin1234**
### IDE.md:
- Added some styling enhancements.
### README.md:
- Added installation steps for the configuration of MySQL for the installation of Alitheia core.
- Added some styling enhancements.

### CODE REVIEW

**Comment by gousiosg** [comment]
Please fix merge conflicts and rebase to latest master commit

**Comment by Sijmen** [comment]
Is it correct now? This is our first pull request.

**Comment by gousiosg** [comment]
You need to do a rebase: this means squashing all intermediate commits (e.g. branch merges) to a single one. Look for commit squashing in the Git book or [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

**Comment by Sijmen** [comment]
I've re-based it, though maybe I've squashed one commit too much.

**Comment by gousiosg** [comment]
Please fix whitespace before line-endings. Also, it would be nice to include example MySQL commands to create the required user and database.

**Comment by gousiosg** [comment]
Please merge conflicts to make this mergeable again, and I will merge it immediately.

**Pull request merged**
