### PR TITLE
Guice core - dependency injection w/ Guice

### PR DESCRIPTION
**Pull request by gkhom**
This pull request adds dependency injection to the Core project of Alitheia Core. Every service is now packaged as a Guice module and is injected as such. Some classes that are instantiated in a non-standard way or outside the reach of the Alitheia Core project (e.g. by utilized frameworks) don't participate in the dependency injection yet. This refactoring removes the God class status of the AlitheiaCore class in the core package.

### CODE REVIEW

**Comment by hermanbanken** [comment]
@gousiosg Can you please explain why this pull request was not merged? While reengineering for this years project we constantly find even our pre-reengineering test efforts limited by the God status of an AlitheiaCore instance. 

For one thing: AlitheiaCore.testInstance() creates an unusable instance by setting the BundleContext parameter to null.

If no further reasons are given, I do expect that every student from this year will start their reengineering with @GeorgiKhomeriki's DI version. Do not reinvent the wheel...

**Comment by gousiosg** [comment]
@hermanbanken It was not merged because it is not working. After the course, @GeorgiKhomeriki did not have time to work on that.

**Comment by hermanbanken** [comment]
@gousiosg Thanks for your clarification. Marieke and I will try getting this to compile(which it now does)/work. DI is great with Mockito.

**Comment by gousiosg** [comment]
:+1:

**Pull request closed without merging**
